[tool.poetry]
name = "paywise-backend-service"
version = "0.1.0"
description = "Paywise Backend service"
authors = ["Mahdi Kafash Kohan <mahdikafashkohan@gmail.com>"]
readme = "README.md"
license = "LICENSE"
homepage = "https://api-paywise.example.com/docs"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
archipy = { extras = ["fastapi", "sqlalchemy", "postgres", "dependency-injection", "cache", "redis", "jwt"], version = ">=3.14.0,<4.0.0" }
alembic = "^1.17.1"
psycopg2-binary = "^2.9.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.23.7"
pre-commit = "^3.7.1"
pre-commit-hooks = "^4.6.0"
codespell = "^2.4.1"
ruff = "^0.7.4"
black = "^24.4.2"
add-trailing-comma = "^3.1.0"
validate-pyproject = "^0.18"
mypy = "^1.14.1"
behave = "^1.2.6"
fastapi-swagger-dark = "0.0.7"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = 'tests'
markers = []
filterwarnings = [
    'error',
    'ignore:This is a placeholder until pydantic-settings.*:UserWarning',
    'ignore::UserWarning',
    'ignore::DeprecationWarning'
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.black]
color = true
line-length = 120
target-version = ["py313"]
skip-string-normalization = false
extend-exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | node_modules
  | __pycache__
)/
'''

[tool.ruff]
fix = true

lint.select = [
    "ALL",
    "D",
    "ERA",
    "F841",
    "I001",
    "N",
    "PTH",
    "Q",
    "RET",
    "S",
    "SIM",
    "TCH",
    "TRY",
    "UP",
]

lint.ignore = [
    "C901",
    "RUF001", "RUF003",
    "PLR2004",
    "Q000",
    "TCH002",
    "PLR0913",
    "E501",
    "F811",
    "S101",
    "S403",
    "S301",
    "D100",
    "D104",
]

src = ["src", "tests", "features"]

exclude = [
    "features/*",
    "scripts/*",
]

line-length = 120
target-version = "py313"

[tool.ruff.lint.per-file-ignores]
"features/steps/*" = ["F811"]
"scripts/*" = ["S603", "S607"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pylint]
max-args = 5
max-branches = 16
max-returns = 16
max-statements = 50

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["src"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = "silent"
no_implicit_reexport = true
pretty = true
python_version = "3.13"
show_error_codes = true
show_error_context = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

plugins = [
    "pydantic.mypy",
]

[[tool.mypy.overrides]]
module = [
    "features.*",
    "scripts.*",
    "redis.*",
    "grpc.*",
    "google.protobuf.*",
    "requests.*",
    "jdatetime.*",
    "sentry_sdk.*",
    "apscheduler.*",
    "archipy.*",
]
ignore_missing_imports = true

[tool.config]
pyproject_root_var = "pyproject"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
