services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis.conf
    env_file:
      - variables.env
    restart: always
    networks:
      - nginx_net
networks:
  nginx_net:
    external: true

volumes:
  redis-data:
