"""empty message

Revision ID: 12664cfc9d02
Revises: 6b9fdbd18d90
Create Date: 2026-02-27 22:17:46.753066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12664cfc9d02"
down_revision: Union[str, Sequence[str], None] = "6b9fdbd18d90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("payment_occurrence_uuid", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("notifications_payment_uuid_fkey"), "notifications", type_="foreignkey")
    op.create_foreign_key(
        None,
        "notifications",
        "payment_occurrences",
        ["payment_occurrence_uuid"],
        ["payment_occurrence_uuid"],
    )
    op.drop_column("notifications", "payment_uuid")
    op.add_column("payment_occurrences", sa.Column("occurrence_index", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_occurrences", "occurrence_index")
    op.add_column("notifications", sa.Column("payment_uuid", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("notifications_payment_uuid_fkey"),
        "notifications",
        "payments",
        ["payment_uuid"],
        ["payment_uuid"],
    )
    op.drop_column("notifications", "payment_occurrence_uuid")
    # ### end Alembic commands ###
