"""empty message

Revision ID: 13ffaefed643
Revises: 3c043ff44882
Create Date: 2026-02-19 21:39:29.510157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13ffaefed643"
down_revision: Union[str, Sequence[str], None] = "3c043ff44882"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("status_type", sa.VARCHAR(length=20), nullable=False))
    op.drop_column("notifications", "status")
    op.alter_column("payment_occurrences", "status_type", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.add_column("payments", sa.Column("payment_type", sa.VARCHAR(length=20), nullable=False))
    op.add_column("payments", sa.Column("category_type", sa.VARCHAR(length=20), nullable=False))
    op.drop_column("payments", "category")
    op.drop_column("payments", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("type", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column("payments", sa.Column("category", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column("payments", "category_type")
    op.drop_column("payments", "payment_type")
    op.alter_column("payment_occurrences", "status_type", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.add_column("notifications", sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column("notifications", "status_type")
    # ### end Alembic commands ###
