"""empty message

Revision ID: 377572d3edd8
Revises: 12664cfc9d02
Create Date: 2026-02-27 22:34:39.005217

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "377572d3edd8"
down_revision: Union[str, Sequence[str], None] = "12664cfc9d02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_notification_occurrence_type",
        "notifications",
        ["payment_occurrence_uuid", "notification_type"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_notification_occurrence_type", "notifications", type_="unique")
    # ### end Alembic commands ###
