"""init

Revision ID: 3c043ff44882
Revises:
Create Date: 2026-02-19 21:15:04.667612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c043ff44882"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("payment_uuid", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category", sa.VARCHAR(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("recurrence_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=True),
        sa.Column("day_of_month_anchor", sa.Integer(), nullable=True),
        sa.Column("total_occurrences", sa.Integer(), nullable=True),
        sa.Column("processed_occurrences", sa.Integer(), nullable=False),
        sa.Column("notify_week_before", sa.Boolean(), nullable=False),
        sa.Column("notify_day_before", sa.Boolean(), nullable=False),
        sa.Column("notify_on_day", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("payment_uuid"),
    )
    op.create_table(
        "notifications",
        sa.Column("notification_uuid", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("payment_uuid", sa.UUID(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.VARCHAR(length=30), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_uuid"],
            ["payments.payment_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("notification_uuid"),
    )
    op.create_table(
        "payment_occurrences",
        sa.Column("payment_occurrence_uuid", sa.UUID(), nullable=False),
        sa.Column("payment_uuid", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("due_datetime", sa.DateTime(), nullable=False),
        sa.Column("status_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_uuid"],
            ["payments.payment_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("payment_occurrence_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_occurrences")
    op.drop_table("notifications")
    op.drop_table("payments")
    # ### end Alembic commands ###
