"""update notification entity with status and is_read

Revision ID: 5985e242b0bf
Revises: a080bba647a5
Create Date: 2026-02-03 03:38:09.382288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5985e242b0bf"
down_revision: Union[str, Sequence[str], None] = "a080bba647a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("status", sa.VARCHAR(length=20), nullable=False))
    op.add_column("notifications", sa.Column("is_read", sa.Boolean(), nullable=False))
    op.alter_column(
        "notifications",
        "notification_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "sent_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notifications",
        "sent_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "notification_type",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("notifications", "is_read")
    op.drop_column("notifications", "status")
    # ### end Alembic commands ###
