"""init

Revision ID: 6b9fdbd18d90
Revises:
Create Date: 2026-02-23 00:38:10.894410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b9fdbd18d90"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_configs",
        sa.Column("app_config_uuid", sa.UUID(), nullable=False),
        sa.Column("force_update_version", sa.String(), nullable=False),
        sa.Column("force_update_message", sa.String(), nullable=True),
        sa.Column("optional_update_version", sa.String(), nullable=False),
        sa.Column("optional_update_message", sa.String(), nullable=True),
        sa.Column("update_link", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("app_config_uuid"),
    )
    op.create_table(
        "users",
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("phone_number", sa.VARCHAR(length=15), nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_username", sa.VARCHAR(length=50), nullable=True),
        sa.Column("username", sa.VARCHAR(length=50), nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(length=255), nullable=True),
        sa.Column("email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("profile_picture_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("user_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("user_status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("gender_type", sa.VARCHAR(length=30), nullable=True),
        sa.Column("fcm_token", sa.VARCHAR(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_uuid"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "files",
        sa.Column("file_uuid", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("path", sa.VARCHAR(length=255), nullable=False),
        sa.Column("is_secured", sa.Boolean(), nullable=False),
        sa.Column("file_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("entity_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("purpose_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("file_uuid"),
    )
    op.create_table(
        "payments",
        sa.Column("payment_uuid", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("payment_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("category_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("recurrence_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=True),
        sa.Column("day_of_month_anchor", sa.Integer(), nullable=True),
        sa.Column("total_occurrences", sa.Integer(), nullable=True),
        sa.Column("processed_occurrences", sa.Integer(), nullable=False),
        sa.Column("notify_week_before", sa.Boolean(), nullable=False),
        sa.Column("notify_day_before", sa.Boolean(), nullable=False),
        sa.Column("notify_on_day", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("payment_uuid"),
    )
    op.create_table(
        "referrals",
        sa.Column("referral_uuid", sa.UUID(), nullable=False),
        sa.Column("referee_uuid", sa.UUID(), nullable=False),
        sa.Column("referer_uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referee_uuid"],
            ["users.user_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["referer_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("referral_uuid"),
    )
    op.create_table(
        "notifications",
        sa.Column("notification_uuid", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("payment_uuid", sa.UUID(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.VARCHAR(length=30), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("status_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_uuid"],
            ["payments.payment_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("notification_uuid"),
    )
    op.create_table(
        "payment_occurrences",
        sa.Column("payment_occurrence_uuid", sa.UUID(), nullable=False),
        sa.Column("payment_uuid", sa.UUID(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("due_datetime", sa.DateTime(), nullable=False),
        sa.Column("status_type", sa.VARCHAR(length=20), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_uuid"],
            ["payments.payment_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("payment_occurrence_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_occurrences")
    op.drop_table("notifications")
    op.drop_table("referrals")
    op.drop_table("payments")
    op.drop_table("files")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("app_configs")
    # ### end Alembic commands ###
