"""empty message

Revision ID: 9cd7f051c003
Revises: 5985e242b0bf
Create Date: 2026-02-12 01:05:28.309103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9cd7f051c003"
down_revision: Union[str, Sequence[str], None] = "5985e242b0bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_id", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("telegram_username", sa.VARCHAR(length=50), nullable=True))
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(length=15), nullable=True)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(length=15), nullable=False)
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
