services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - nginx_net
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/:/etc/nginx/logs/
      - ./cert/cert.pem:/etc/nginx/server.crt
      - ./cert/key.pem:/etc/nginx/server.key


networks:
  nginx_net:
    name: nginx_net
    external: true
