name: 'Deploy to VPS'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/paywise-backend-service
            git fetch --tags
            git checkout ${{ env.VERSION }}
            git pull origin main
            sudo docker build -t paywise-backend:${{ env.VERSION }} .
            sudo docker tag paywise-backend:${{ env.VERSION }} paywise-backend:latest
            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose.prod.yml up -d
            sudo docker image prune -f
            echo "Deployed version ${{ env.VERSION }} successfully"
